version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hr_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8083
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=hr_app_db
      - DB_USER=hr_app_user
      - DB_PASSWORD=hr_app_pass
      - DB_HOST=db
      - DB_PORT=5432
      - GROQ_API_KEY={{groq_api_key}}
    links:
      - db

volumes:
  postgres_data:
